name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up SSH
          uses: webfactory/ssh-agent@v0.5.4
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
        - name: Verify SSH Access
          run: ssh -o StrictHostKeyChecking=no ubuntu@150.136.4.181 'echo SSH connection successful'
  
        - name: Pull from Repository
          run: ssh -o StrictHostKeyChecking=no ubuntu@150.136.4.181 'cd Back-End-Bubbly && git pull origin main'
